version: '3.8'

services:
  streamlit-app:
    build:
      context: .  
      dockerfile: app/Dockerfile
    env_file:
      - .env
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - postgres_network

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data  # Ensure PGDATA is explicitly set
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Named volume
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - postgres_network

volumes:
  postgres_data:  # Ensure this section is included

networks:
  postgres_network:
    driver: bridge
