services:
  streamlit-app:
    build:
      context: .  
      dockerfile: app/Dockerfile
    env_file:
      - .env
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - ticket-app_postgres_network

  api:
    build:
      context: .  
      dockerfile: api/Dockerfile
    env_file:
      - .env
    container_name: api
    ports:
      - "5001:5000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - ticket-app_postgres_network 

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      retries: 5
    networks:
      - ticket-app_postgres_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "7552:80"
    depends_on:
      - db
    networks:
      - ticket-app_postgres_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
    ports:
      - "3013:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - db
    networks:
      - ticket-app_postgres_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090"
    networks:
      - ticket-app_postgres_network

  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ticket-app_postgres_network
  
  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    container_name: redis-commander
    ports:
      - "8316:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379:0:${REDIS_PASSWORD}
      - HTTP_USER=${REDIS_UI_USERNAME}
      - HTTP_PASSWORD=${REDIS_UI_PASSWORD}
      - HTTP_AUTH_ENABLED=true
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - ticket-app_postgres_network

  wa-bot:
    container_name: wa-bot
    build:
      dockerfile: wa-bot/Dockerfile
    restart: unless-stopped
    volumes:
      - ./wa-bot/auth_info:/usr/server/wa-bot/auth_info
    depends_on:
      - redis
      - api
    networks:
      - ticket-app_postgres_network 

volumes:
  postgres_data:
  grafana_data:
  redis_data:
    name: whatsapp_bot_redis_data

networks:
  ticket-app_postgres_network:
    driver: bridge
