version: '3.8'

services:
  #streamlit-app:
  #  build: ./app
  #  container_name: streamlit_app
  #  ports:
  #    - "8501:8501"
  #  depends_on:
  #    - db
  #  environment:
  #    - DATABASE_URL=postgresql://postgres:postgres@db:5432/tickets_db
  #  volumes:
  #    - ./app:/app

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tickets_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
